#! /bin/bash


echo "Copying over ssh keys..."
for file in $(find /vagrant/custom/.ssh -type f -printf "%f\n")
do
	cp /vagrant/custom/.ssh/$file /home/vagrant/.ssh/$file
	chmod 600 /home/vagrant/.ssh/$file
done
eval `ssh-agent`

echo "eval `ssh-agent`" >> /home/vagrant/.bashrc
