#!/bin/bash

# Make sure only root can run
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

yum install -y gcc make
yum install -y "kernel-devel-uname-r == $(uname -r)"
yum groupinstall -y "X Window System"

pushd /tmp
# at this location is a file called LATEST.txt (I think) that has the latest version number
wget http://download.virtualbox.org/virtualbox/5.1.12/VBoxGuestAdditions_5.1.12.iso

mkdir -p /media/cdrom
mount VBoxGuestAdditions_5.1.12.iso /media/cdrom
/media/cdrom/VBoxLinuxAdditions.run

popd

